Fix plugin for Sketch 86
Error due to Sketch refactoring: NSColorSpace to CGColorSpace

TypeError: null is not an object (evaluating 'bitmapRepresentation.CGImage')

https://sketchplugins.com/d/2467-error-evaluating-bitmaprepresentationcgimage-after-sketch-86-update